### ISSUE TITLE
To-Do Stuff & Public Requests

### ISSUE THREAD

**Issue by TriForceX** [TriForceX/JediKnightPlus#5]
There is the list of unfinished stuff and people's approved requests. As i go forward, i will move the items to the main list of mod features:

- [ ] Add Unlagged Feature
- [ ] Enable lightsaber physics on dead corpses
- [ ] Possibility to do force powers on NPC's
- [ ] Add Telefrag (Show the camera on the last killer)
- [ ] In-game screenshot viewer
- [ ] Add Light-Amp Goggles item from single player
- [ ] Add Flashlight feature
- [ ] Enable voice commands (Jedi Academy style)
- [ ] Add Hold The Point game type
- [ ] Add Man Hunt or Captains game type
- [ ] Add Jedi Academy Radar for team games
- [ ] In-game MP3 player
- [ ] Portal Gun teleport weapon mechanics
